In [ ]:
import numpy
hugeNumber = float("inf")
stages = 10
startInventory = 0
inventoryCapacity = 20
productionCapacity = 15
setupCost = 3.0
variableCost = 1.0
holdingCost = 0.5
demand = numpy.array([-1000,1,3,2,4,6,10,4,2,8,9])
f = numpy.zeros([stages + 2, inventoryCapacity + 1])
x = numpy.zeros([stages + 1, inventoryCapacity + 1], dtype=int)
# In other problems, we may initialize f[i,stages + 1] at this point
# But in this problem, these values can just stay 0
for t in range(stages, 0, -1):
  for i in range(inventoryCapacity + 1):
    minProduction = max(0, demand[t] - i)
    maxProduction = min(productionCapacity, inventoryCapacity - i + demand[t])
    value = hugeNumber
    for p in range(minProduction, maxProduction + 1):
        j = i + p - demand[t]
        productionCost = setupCost*numpy.sign(p) + variableCost * p
        moveValue = holdingCost*j + productionCost + f[t + 1, j]
        if moveValue < value:
          value = moveValue
          bestMove = p
  # End of p loop
    f[t, i] = value
    x[t, i] = bestMove
# End of i loop
# End of t loop
print("Optimal cost is " + str(f[1, startInventory]))
solutionString = "Production amounts:"
i = startInventory
for t in range(1, stages + 1):
  solutionString += " " + str(x[t, i])
  i = i + x[t, i] - demand[t]
print(solutionString)

Optimal cost is 74.5
Production amounts: 4 0 6 0 6 10 6 0 8 9


In [ ]:
import numpy as np

hugeNumber = float("inf")

# Define parameters
sell_price = np.array([2500, 2800, 2000, 2700])
buy_price = np.array([2600, 2900, 2100, 2800])
holding_cost = 100
salvage_value = 2000

# Number of stages (months)
stages = len(sell_price)

# Initialize matrices
f = np.zeros([stages + 2, 3])
x = np.zeros([stages + 1, 3], dtype=int)

# Set terminal values
f[stages + 1, :] = salvage_value - holding_cost

# Dynamic programming to fill in the value function matrix
for t in range(stages, 0, -1):
    for i in range(3):
        value = -hugeNumber  # maximizing
        for d in range(3):
            if d == 0 and i < 2:
                j = i + 1
                move_value = -buy_price[t - 1] - holding_cost + f[t + 1, j]
            elif d == 1:
                j = i
                move_value = f[t + 1, j]
            elif d == 2 and i > 0:
                j = i - 1
                move_value = sell_price[t - 1] - holding_cost + f[t + 1, j]
            else:
                move_value = -hugeNumber

            if move_value > value:
                value = move_value
                best_move = d

        f[t, i] = value
        x[t, i] = best_move

# Print the optimal solution
print("Optimal solution is " + str(f[1, 0]))
print("Optimal Strategy:")
i = 0  # initial state
for t in range(1, stages + 1):
    decision = x[t, i]
    if decision == 0:
        print(f"Month {t}: Buy")
        i += 1
    elif decision == 1:
        print(f"Month {t}: Hold")
    elif decision == 2:
        print(f"Month {t}: Sell")
        i -= 1
    i = max(0, i)

# Print ending state if desired
# print("Ending state: " + str(i))
print(f)
print(x)

Optimal solution is 2300.0
Optimal Strategy:
Month 1: Buy
Month 2: Sell
Month 3: Buy
Month 4: Sell
[[   0.    0.    0.]
 [2300. 5000. 7400.]
 [2300. 5000. 7200.]
 [2300. 4500. 6400.]
 [1900. 4500. 4500.]
 [1900. 1900. 1900.]]
[[0 0 0]
 [0 1 2]
 [1 2 2]
 [0 1 2]
 [1 2 2]]


In [ ]:
# Python code for integer knapsack problem, with numpy
import numpy
hugeNumber = float("inf")
unused = -1000 # Dummy value to make code more readable
capacity = 30
# "unused" is for element 0, which we don't use
itemWeight = numpy.array([unused, 4, 3, 5, 6, 8, 9])
itemValue = numpy.array([unused, 11, 7, 12, 15, 22, 25])
# Number of stages is number of items. Figure this out from
# the length of the data array (not counting the "unused" element)
stages = len(itemWeight) - 1
f = numpy.zeros([stages + 2, capacity + 1])
x = numpy.zeros([stages + 1, capacity + 1], dtype=int)
for t in range(stages, 0, -1): # Loop stages, stages-1, ... , 1
  for i in range(capacity + 1): # Loop over all possible amounts
# of space left (0 to capacity)
    maxCanFit = int(i / itemWeight[t]) # How many will fit? (int rounds down)
    value = -hugeNumber # Because we're maximizing
    for d in range(maxCanFit + 1): # Loop d from 0 to maxCanFit
      j = i - d*itemWeight[t]
      moveValue = d*itemValue[t] + f[t + 1, j]
      if moveValue > value: # > here because we're maximizing
        value = moveValue
        bestMove = d
# End of d loop
    f[t, i] = value
    x[t, i] = bestMove
# End of i loop
# End of t loop
print("Optimal value is " + str(f[1, capacity]))
print("Item counts:")
i = capacity
for t in range(1, stages + 1):
  print(str(x[t, i]) + " of type " + str(t))
  i = i - x[t, i] * itemWeight[t]
print("Unused space is " + str(i))
print(f)
print(x)

Optimal value is 83.0
Item counts:
1 of type 1
0 of type 2
0 of type 3
0 of type 4
1 of type 5
2 of type 6
Unused space is 0
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  7. 11. 12. 15. 18. 22. 25. 26. 29. 33. 36. 37. 40. 44. 47.
  50. 51. 55. 58. 61. 62. 66. 69. 72. 75. 77. 80. 83.]
 [ 0.  0.  0.  7.  7. 12. 15. 15. 22. 25. 25. 29. 32. 34. 37. 40. 44. 47.
  50. 51. 54. 57. 59. 62. 66. 69. 72. 75. 76. 79. 82.]
 [ 0.  0.  0.  0.  0. 12. 15. 15. 22. 25. 25. 27. 30. 34. 37. 40. 44. 47.
  50. 50. 52. 56. 59. 62. 66. 69. 72. 75. 75. 78. 81.]
 [ 0.  0.  0.  0.  0.  0. 15. 15. 22. 25. 25. 25. 30. 30. 37. 40. 44. 47.
  50. 50. 52. 55. 59. 62. 66. 69. 72. 75. 75. 77. 81.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 22. 25. 25. 25. 25. 25. 25. 25. 44. 47.
  50. 50. 50. 50. 50. 50. 66. 69. 72. 75. 75. 75. 75.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. 25. 25. 25. 25. 25. 25. 25. 25. 25.
  50. 50. 50. 50. 50. 50. 5

In [ ]:
import numpy
hugeNumber = float("inf")
unused = -1000
# Initialize all needed parameters and data
stages = 3
capital = 4
# Input data table. "Unused" is for column 0
npv = numpy.array([[unused, 4, 3, 3],
[unused, 7, 6, 7],
[unused, 8, 10, 8],
[unused, 9, 12, 13],
[unused, 11, 14, 15]])

# Initialize all needed parameters and data here
f = numpy.zeros([stages + 2, capital + 1])
x = numpy.zeros([stages + 1, capital + 1], dtype = int)
# If not zero, set each f[stages+1,i] to the terminal value of being in state i at the end
# For states that are not allowed, use hugenumber for minimization, -hugenumber for maximization
for t in range(stages, 0, -1):
# If necessary, determine which states are possible at stage t
# (This is usually not necessary in the examples in this class)
  for i in range(capital + 1):
# Determine set of decisions d which are possible from this state and stage
    value = -hugeNumber
    for d in range(i + 1):
      j = i - d
      # Compute immediate costs and/or rewards from decision d
      moveValue = npv[d,t] + f[t + 1, j]
      if moveValue > value: # use < instead of > if minimizing
        value = moveValue
        bestMove = d
# End of d loop
    f[t, i] = value
    x[t, j] = bestMove
# End of i loop
# End of t loop
print("Optimal solution is " + str(f[1, capital]))
print("Investment amounts")
i = capital
for t in range(1, stages + 1):
  print("invest " + str(x[t, i]) + " in project " + str(t))
  i = i - x[t,i]
# Optionally, you can print something about ending state here
print(f)
print(x)

Optimal solution is 24.0
Investment amounts
invest 0 in project 1
invest 0 in project 2
invest 0 in project 3
[[ 0.  0.  0.  0.  0.]
 [10. 14. 17. 21. 24.]
 [ 6. 10. 13. 17. 19.]
 [ 3.  7.  8. 13. 15.]
 [ 0.  0.  0.  0.  0.]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [4 0 0 0 0]]


In [ ]:
# Python code for simple probabilistic inventory by dynamic programming
import numpy
hugeNumber = float("inf")
unused = -1000
stages = 3
startInventory = 1
inventoryCapacity = 3
productionCapacity = 4
setupCost = 3.0
variableCost = 2.0
holdingCost = 1.0
salvageValue = 2.0
minDemand = 1
maxDemand = 2
# demandProb[t,d] is probability demand will be d in period t
demandProb = numpy.array([[unused, unused, unused],
[0.0, 0.5, 0.5],
[0.0, 0.5, 0.5],
[0.0, 0.5, 0.5]])
f = numpy.zeros([stages + 2, inventoryCapacity+1])
x = numpy.zeros([stages + 1, inventoryCapacity+1], dtype=int)
# Set the value of ending up in each final state (not zero in this case)
for i in range(inventoryCapacity + 1) :
  f[stages+1,i] = -salvageValue*i # Negative "cost" = benefit
# for each leftover unit
for t in range(stages,0,-1) :
  for i in range(inventoryCapacity+1) :
    minProduction = max(0, maxDemand - i)
    maxProduction = min(productionCapacity, inventoryCapacity - i + minDemand)
    value = hugeNumber
    bestMove = None
    for p in range(minProduction, maxProduction+1) :
    # Initialize moveValue to the production cost (this cost does not depend on demand)
      moveValue = setupCost*numpy.sign(p) + variableCost*p
# Accumulate expected value of this decision
      for d in range(minDemand,maxDemand+1) :
          j = i + p - d
          moveValue += demandProb[t,d]*(holdingCost*j + f[t+1,j])
      if moveValue < value :
          value = moveValue
          bestMove = p
# End of p loop
    f[t,i] = value
    x[t,i] = bestMove
# End of i loop
# End of t loop
print("Optimal expected cost is " + str(f[1,startInventory]))
print("Period 1: produce " + str(x[1,startInventory]))
for t in range(2,stages+1) :
  print("Period " + str(t) + ":")
  for i in range(inventoryCapacity + 1) :
    print(" If inventory=" + str(i) + ", produce " + str(x[t,i]))


Optimal expected cost is 16.25
Period 1: produce 3
Period 2:
 If inventory=0, produce 3
 If inventory=1, produce 2
 If inventory=2, produce 0
 If inventory=3, produce 0
Period 3:
 If inventory=0, produce 2
 If inventory=1, produce 1
 If inventory=2, produce 0
 If inventory=3, produce 0


In [ ]:
# Python code for simple probabilistic inventory by dynamic programming
import numpy
hugeNumber = float("inf")
unused = -1000
stages = 5
startInventory = 1
inventoryCapacity = 10
productionCapacity = 10
setupCost = 10.0
variableCost = 2.0
holdingCost = 1.0
salvageValue = 2.0
minDemand = 0
maxDemand = 4
demandProb = numpy.array([[unused]*5,
[0.20, 0.20, 0.20, 0.20, 0.20],
[0.10, 0.20, 0.30, 0.20, 0.10],
[0.30, 0.30, 0.20, 0.15, 0.05],
[0.30, 0.25, 0.20, 0.15, 0.10],
[0.20, 0.20, 0.20, 0.20, 0.20]])
f = numpy.zeros([stages + 2, inventoryCapacity+1])
x = numpy.zeros([stages + 1, inventoryCapacity+1], dtype=int)
# Set the value of ending up in each final state (not zero in this case)
for i in range(inventoryCapacity + 1) :
  f[stages+1,i] = -salvageValue*i # Negative "cost" = benefit
# for each leftover unit
for t in range(stages,0,-1) :
  for i in range(inventoryCapacity+1) :
    minProduction = max(0, maxDemand - i)
    maxProduction = min(productionCapacity, inventoryCapacity - i + minDemand)
    value = hugeNumber
    bestMove = None
    for p in range(minProduction, maxProduction+1) :
    # Initialize moveValue to the production cost (this cost does not depend on demand)
      moveValue = setupCost*numpy.sign(p) + variableCost*p
# Accumulate expected value of this decision
      for d in range(minDemand,maxDemand+1) :
          j = i + p - d
          moveValue += demandProb[t,d]*(holdingCost*j + f[t+1,j])
      if moveValue < value :
          value = moveValue
          bestMove = p
# End of p loop
    f[t,i] = value
    x[t,i] = bestMove
# End of i loop
# End of t loop
print("Optimal expected cost is " + str(f[1,startInventory]))
print("Period 1: produce " + str(x[1,startInventory]))
for t in range(2,stages+1) :
  print("Period " + str(t) + ":")
  for i in range(inventoryCapacity + 1) :
    print(" If inventory=" + str(i) + ", produce " + str(x[t,i]))


Optimal expected cost is 54.500350000000005
Period 1: produce 7
Period 2:
 If inventory=0, produce 8
 If inventory=1, produce 7
 If inventory=2, produce 6
 If inventory=3, produce 5
 If inventory=4, produce 0
 If inventory=5, produce 0
 If inventory=6, produce 0
 If inventory=7, produce 0
 If inventory=8, produce 0
 If inventory=9, produce 0
 If inventory=10, produce 0
Period 3:
 If inventory=0, produce 7
 If inventory=1, produce 6
 If inventory=2, produce 5
 If inventory=3, produce 4
 If inventory=4, produce 0
 If inventory=5, produce 0
 If inventory=6, produce 0
 If inventory=7, produce 0
 If inventory=8, produce 0
 If inventory=9, produce 0
 If inventory=10, produce 0
Period 4:
 If inventory=0, produce 6
 If inventory=1, produce 5
 If inventory=2, produce 4
 If inventory=3, produce 3
 If inventory=4, produce 0
 If inventory=5, produce 0
 If inventory=6, produce 0
 If inventory=7, produce 0
 If inventory=8, produce 0
 If inventory=9, produce 0
 If inventory=10, produce 0
Period 5:
 I

In [ ]:
import numpy

hugeNumber = float("inf")
unused = -1000
stages = 12
startInventory = 2
inventoryCapacity = 20
holdingCost = 0.80
smallQPrice = 10.00
bigQPrice = 8.00
priceBreakPoint = 5
demand = numpy.array([unused, 5, 6, 5, 6, 7, 3, 4, 3, 8, 5, 4, 5])

# Initialize arrays
f = numpy.zeros([stages + 2, inventoryCapacity + 1])
x = numpy.zeros([stages + 1, inventoryCapacity + 1], dtype=int)

# In other problems, we may initialize f[i,stages + 1] at this point
# But in this problem, these values can just stay 0
for t in range(stages, 0, -1):
  for i in range(inventoryCapacity + 1):
    minProduction = max(0, demand[t] - i)
    maxProduction = (inventoryCapacity - i + demand[t])
    value = hugeNumber
    for p in range(minProduction, maxProduction + 1):
        j = i + p - demand[t]
        ordering_cost = smallQPrice * min(p, priceBreakPoint) + bigQPrice * max(0, p - priceBreakPoint)
        moveValue = holdingCost*j + ordering_cost + f[t + 1, j]
        if moveValue < value:
          value = moveValue
          bestMove = p
  # End of p loop
    f[t, i] = value
    x[t, i] = bestMove
# End of i loop
# End of t loop

# Print decision and explanation
print("Optimal cost is " + str(f[1, startInventory]))
solutionString = "Production amounts:"
i = startInventory
for t in range(1, stages + 1):
  solutionString += " " + str(x[t, i])
  i = i + x[t, i] - demand[t]
print(solutionString)

# Optionally, you can print something about the ending state here
print("Ending inventory at month 12 is", i)


Optimal cost is 552.8
Production amounts: 3 11 0 16 0 0 7 0 13 0 9 0
Ending inventory at month 12 is 0
